#!/usr/bin/python3

import dns.resolver

from rkn import RKNDump
from iproute2 import IPRoute2
from tools import get_af

import settings

def main():
    dump = RKNDump(settings.dumpurl)
    #dump.stateSave()

    for addr in settings.add_to_list:
      try:
        af = get_af(addr)
      except ValueError as e:
        dump.ipbase |= set([i.to_text() for i in dns.resolver.query(name, 'a')])
      else:
        dump.ipbase |= set([addr])

    dump.ipbase -= set(settings.rm_from_list)

    ips = IPRoute2(settings.scope, settings.target4, settings.target6)

    to_add, to_rm = dump.diff(ips.addresses)

    ips.change(to_add, to_rm)

if __name__ == "__main__":
    main()
